# yaml-language-server: $schema=./configSchema.json
pages:
  - url: https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#get-started
    frequency: daily
    nextOpening: 2025-02-26T15:12:18Z
     
  - url: https://onedrive.live.com/redir?resid=3981CA5E56F3AD91%
    frequency: weekly
    
  # - url: https://www.example4.com
  #   frequency: quarterly
